// dropdownData.js

export const interestsOptions = [
  { label: 'Movies & TV', value: 'movies_tv' },
  { label: 'Gaming', value: 'gaming' },
  { label: 'Photography', value: 'photography' },
  { label: 'Fashion', value: 'fashion' },
  { label: 'Writing', value: 'writing' },
  { label: 'Nature', value: 'nature' },
  { label: 'Animals', value: 'animals' },
  { label: 'Volunteering', value: 'volunteering' },
  { label: 'History', value: 'history' },
  { label: 'Science', value: 'science' },
  { label: 'Cars & Motorcycles', value: 'cars_motorcycles' },
  { label: 'Podcasts', value: 'podcasts' },
  { label: 'Crafts & DIY', value: 'crafts_diy' },
  { label: 'Spirituality', value: 'spirituality' },
  { label: 'Board Games', value: 'board_games' },
  { label: 'Languages', value: 'languages' },
  { label: 'Politics', value: 'politics' },
  { label: 'Comedy', value: 'comedy' },
  { label: 'Entrepreneurship', value: 'entrepreneurship' },
  { label: 'Collecting', value: 'collecting' },
]
export const ethnicityOptions = [
    { label: 'Middle Eastern', value: 'middle_eastern' },
    { label: 'Native American', value: 'native_american' },
    { label: 'Pacific Islander', value: 'pacific_islander' },
    { label: 'South Asian', value: 'south_asian' },
    { label: 'Southeast Asian', value: 'southeast_asian' },
    { label: 'East Asian', value: 'east_asian' },
    { label: 'Central Asian', value: 'central_asian' },
    { label: 'North African', value: 'north_african' },
    { label: 'Afro-Caribbean', value: 'afro_caribbean' },
    { label: 'Latinx', value: 'latinx' },
    { label: 'Multiracial', value: 'multiracial' },
    { label: 'Prefer Not to Say', value: 'prefer_not_to_say' },
  ];
  
  export const pastActivitiesOptions = [
    { label: 'Cardio', value: 'Cardio' },
    { label: 'Board Games', value: 'Board Games' },
    { label: 'Martial Arts', value: 'Martial Arts' },
    { label: 'Climbing', value: 'Climbing' },
    { label: 'Skating', value: 'Skating' },
    { label: 'Winter Sports', value: 'Winter Sports' },
    { label: 'Running', value: 'Running' },
    { label: 'Cycling', value: 'Cycling' },
    { label: 'Yoga', value: 'Yoga' },
    { label: 'Pilates', value: 'Pilates' },
    { label: 'Hiking', value: 'Hiking' },
    { label: 'Fishing', value: 'Fishing' },
    { label: 'Camping', value: 'Camping' },
    { label: 'Traveling', value: 'Traveling' },
    { label: 'DIY Projects', value: 'DIY Projects' },
    { label: 'Esports', value: 'Esports' },
    { label: 'Parkour', value: 'Parkour' },
    { label: 'Archery', value: 'Archery' },
    { label: 'Surfing', value: 'Surfing' },
    { label: 'Horseback Riding', value: 'Horseback Riding' },
  ];
  
  export const personalityOptions = [
    { label: 'Curious', value: 'Curious' },
    { label: 'Empathetic', value: 'Empathetic' },
    { label: 'Adventurous', value: 'Adventurous' },
    { label: 'Thoughtful', value: 'Thoughtful' },
    { label: 'Creative', value: 'Creative' },
    { label: 'Analytical', value: 'Analytical' },
    { label: 'Spontaneous', value: 'Spontaneous' },
    { label: 'Organized', value: 'Organized' },
    { label: 'Playful', value: 'Playful' },
    { label: 'Calm', value: 'Calm' },
    { label: 'Driven', value: 'Driven' },
    { label: 'Loyal', value: 'Loyal' },
    { label: 'Independent', value: 'Independent' },
    { label: 'Funny', value: 'Funny' },
    { label: 'Romantic', value: 'Romantic' },
    { label: 'Open-Minded', value: 'Open-Minded' },
    { label: 'Optimistic', value: 'Optimistic' },
    { label: 'Realistic', value: 'Realistic' },
    { label: 'Cautious', value: 'Cautious' },
    { label: 'Chill', value: 'Chill' },
  ];
  
  export const occupationOptions = [
    { label: 'Technology', value: 'technology' },
    { label: 'Healthcare & Medicine', value: 'healthcare_medicine' },
    { label: 'Education', value: 'education' },
    { label: 'Finance & Accounting', value: 'finance_accounting' },
    { label: 'Arts & Entertainment', value: 'arts_entertainment' },
    { label: 'Engineering', value: 'engineering' },
    { label: 'Law & Government', value: 'law_government' },
    { label: 'Marketing & Advertising', value: 'marketing_advertising' },
    { label: 'Retail & Sales', value: 'retail_sales' },
    { label: 'Science & Research', value: 'science_research' },
    { label: 'Hospitality & Tourism', value: 'hospitality_tourism' },
    { label: 'Construction & Trade', value: 'construction_trade' },
    { label: 'Transportation & Logistics', value: 'transportation_logistics' },
    { label: 'Non-Profit & Advocacy', value: 'nonprofit_advocacy' },
    { label: 'Media & Communication', value: 'media_communication' },
    { label: 'Real Estate', value: 'real_estate' },
    { label: 'Sports & Recreation', value: 'sports_recreation' },
    { label: 'Business & Entrepreneurship', value: 'business_entrepreneurship' },
    { label: 'Agriculture & Environment', value: 'agriculture_environment' },
    { label: 'Other', value: 'other' },
  ];