name: Frontend CI

on:
  push:
    paths:
      - 'Pair/**'
      - '.github/workflows/frontend.yml'
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd Pair
        npm ci

    - name: Run Linter
      run: |
        cd Pair
        npm run lint
